FROM node:20-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY tsconfig.json tsconfig.build.json nest-cli.json ./
COPY libs/ libs/
COPY src/ src/
COPY scripts/ scripts/

RUN pnpm prisma generate --schema=libs/prisma/schema.prisma

RUN pnpm build

CMD node dist/src/main
